ServerEvents.highPriorityData(event => {
    function registerModules(key, registryModel) {
        let slots = registryModel.slots[0].split('/')[0]
        event.addJson(`tetra:modules/${slots}/${key}.json`, registryModel)
    }

    registerModules('drill', new ModulesRegistry()
        .addSlots('single/head')
        .addImprovements('tetra:single/shared_head/')
        .addImprovements('tetra:single/shared/')
        .addImprovements('tetra:shared/')
        .addVariants(new VariantsRegistry('drill/')
            .setMaterials('tetra:drill/')
            .setBasic(0, 120, 0)
            .setGlyph(224, 32)
            .setModels('tetra:items/module/single/head/drill/')
            .addAspects('blockBreaker', 2)
            .addAspects('breakable', 2)
            .addTools('shovel_dig', [0, -2])
            .addTools('pickaxe_dig', [0, -4])
            .setExtract(['iron', 'diamond', 'netherite'])
            .addPrimaryAttributes({ 'generic.attack_damage': 1 })
            .addSecondaryAttributes({ 'generic.attack_speed': -0.15 })
            .addExtractTools({ 'shovel_dig': [0.8, 0.8] })
            .addExtractTools({ 'pickaxe_dig': [0.8, 0.8] })
            .setExtractBasic(-1, 0.6, 1)
        )
    )
    // let j = new ModulesRegistry()
    //     .addSlots('single/head')
    //     .addImprovements('tetra:single/shared_head/')
    //     .addImprovements('tetra:single/shared/')
    //     .addImprovements('tetra:shared/')
    //     .addVariants(new VariantsRegistry('drill/')
    //         .setMaterials('tetra:drill/')
    //         .setBasic(0, 120, 0)
    //         .setGlyph(224, 32)
    //         .setModels('tetra:items/module/single/head/drill/')
    //         .addAspects('blockBreaker', 2)
    //         .addAspects('breakable', 2)
    //         .addTools('shovel_dig', [0, -2])
    //         .addTools('pickaxe_dig', [0, -4])
    //         .setExtract(['iron', 'diamond', 'netherite'])
    //         .addPrimaryAttributes({ 'generic.attack_damage': 1 })
    //         .addSecondaryAttributes({ 'generic.attack_speed': -0.15 })
    //         .addExtractTools({ 'shovel_dig': [0.8, 0.8] })
    //         .addExtractTools({ 'pickaxe_dig': [0.8, 0.8] })
    //         .setExtractBasic(-1, 0.6, 1)
    //     )
    // let j1 = JSON.stringify(j, null, 4)
    // console.log(j1)
    
    
    
})