ServerEvents.highPriorityData(event => {
    function registerSchematics(key, registryModel) {
        let slot = registryModel.slots[0]
        event.addJson(`tetra:schematics/${slot}/${key}/${key}.json`, registryModel)
    }
    registerSchematics('drill', new SchematicsRegistry()
        .addSlots('single/head')
        .setMaterialSlotCount()
        .setRarity('major')
        .setGlyph(224, 32)
        .setTranslation(new TranslationRegistry()
            .addPrimaryAttributes({ 'generic.attack_damage': 2 })
            .addSecondaryAttributes({ 'generic.attack_speed': -1 })
            .addTools({ 'shovel_dig': [0.8, 0.4] })
            .addTools({ 'pickaxe_dig': [0.8, 0.4] })
            .setBasic(-3, 3, 3)
        )
        .setOutcomes(new OutcomesRegistry('tetra:drill/')
            .setModule('single/drill', 'drill/')
        )
    )
    // let j = new SchematicsRegistry()
    //     .addSlots('single/head')
    //     .setMaterialSlotCount()
    //     .setRarity('major')
    //     .setGlyph(224, 32)
    //     .setTranslation(new TranslationRegistry()
    //         .addPrimaryAttributes({ 'generic.attack_damage': 2 })
    //         .addSecondaryAttributes({ 'generic.attack_speed': -1 })
    //         .addTools({ 'shovel_dig': [0.8, 0.4] })
    //         .addTools({ 'pickaxe_dig': [0.8, 0.4] })
    //         .setBasic(-3, 3, 3)
    //     )
    //     .setOutcomes(new OutcomesRegistry('tetra:drill/')
    //         .setModule('single/drill', 'drill/')
    // )
    // let j1 = JSON.stringify(j, null, 4)

    // console.log(j1)
})